### ISSUE TITLE
.gitignore file for the repository

### ISSUE THREAD

**Issue by SusheelThapa** [prasad-chavan1/Animesthetic-Social-Media#19]

**Comment by Quinos2003** [comment]
can i pick this?

**Comment by prasad-chavan1** [comment]
> can i pick this?

Go with chat section issue

**Comment by SusheelThapa** [comment]
@prasad-chavan1  assign me this

**Comment by prasad-chavan1** [comment]
> @prasad-chavan1 assign me this

Go with chat section issue provide any figma design or build impressive Frontend for that

**Comment by SusheelThapa** [comment]
@prasad-chavan1  I am backend developer. Feel free to contact me.

**Comment by prasad-chavan1** [comment]
> @prasad-chavan1 I am backend developer. Feel free to contact me.

Yeah buddy sure... Start contributing on chat section backend issue i mean create DB models for chat section

**Comment by SusheelThapa** [comment]
![Screenshot from 2023-10-04 05-52-56](https://github.com/prasad-chavan1/Animesthetic-Social-Media/assets/83917129/23eac3d3-793e-4920-a4b1-14a9f230fe4d)


In absence of .gitignore files following unwanted files has been added to the repository, like __pycache__

**Comment by prasad-chavan1** [comment]
> ![Screenshot from 2023-10-04 05-52-56](https://user-images.githubusercontent.com/83917129/272428278-23eac3d3-793e-4920-a4b1-14a9f230fe4d.png)
> 
> In absence of .gitignore files following unwanted files has been added to the repository, like **pycache**

Okay try adding .gitignore
