### ISSUE TITLE
Show more doesn't load more users

### ISSUE THREAD

**Issue by Quinos2003** [prasad-chavan1/Animesthetic-Social-Media#20]
On the right side of page show where suggest to follow people come show more doesn't load more users. I think no api is getting called when we click on it.

**Comment by Quinos2003** [comment]
![image](https://github.com/prasad-chavan1/Animesthetic-Social-Media/assets/72240452/2e4e9961-79d0-499e-9034-70ed9f79d5f7)

**Comment by prasad-chavan1** [comment]
> On the right side of page show where suggest to follow people come show more doesn't load more users. I think no api is getting called when we click on it.

Ysss thats bug fix that bug if you can 😄

**Comment by malay5** [comment]
@prasad-chavan1 can you please assign this to me?

**Comment by prasad-chavan1** [comment]
> @prasad-chavan1 can you please assign this to me?

assigned raisee PR
